version: '3.1'

services:

  wordpress:
    image: wordpress:6.1.1
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mjgarganis_lab
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/mjgargani-style

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mjgarganis_lab
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  wordpress:
  db: