version: '3.1'

services:

  wordpress:
    image: wordpress:6.1.1-fpm-alpine
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: mjgarganis_lab
    volumes:
      - wordpress:/var/www/html
      - ./theme:/var/www/html/wp-content/themes/mjgargani-style
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:8080"]
      timeout: 10s
      retries: 5

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: mjgarganis_lab
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

volumes:
  wordpress:
  db: